backend/blog/urls.py
from django.urls import path
from .views import blog_post_list, blog_post_detail, PostListView


app_name = 'blog'

urlpatterns = [
    #path('', blog_post_list, name='blog_posts_list_url'),
    path('', PostListView.as_view(), name='blog_posts_list_url'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         blog_post_detail,
         name='blog_post_detail_url'),
]

maxcoder_config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, ),
    path('', include('backend.pages.urls')),
    path('', include('allauth.urls')),
    path('blog/', include('backend.blog.urls', namespace='blog')),
    path('store/', include('backend.store.urls', namespace='store')),
    path('accounts/', include('backend.profile.urls')),

]

if settings.DEBUG:
    from django.views.static import serve
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

src/templates/base/base.html
<!DOCTYPE html>  {% load static %} {% load yandex_metrica %}
<html lang="ru">

<head>

    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <meta name="description" content=""/>
    <meta name="author" lang="en" content="Pritvor69"/>
    <meta name="copyright" lang="en" content="maxcoder.ru"/>
    <title>{{ pagename }}</title>
    <link rel="apple-touch-icon" sizes="180x180" href={% static "base/img/favicon180*180.png" %}>
    <link rel="icon" type="image/png" sizes="32x32" href={% static "base/img/favicon32*32.png" %}>

    <!-- CSS -->
    <link rel="stylesheet" href={% static "base/css/bootstrap-grid.css" %}>
    <link rel="stylesheet" href={% static "base/css/style_base.css" %}>
    <link rel="stylesheet" href={% static "base/css/font-awesome.min.css" %}>
    {% block render_css %}{% endblock render_css %}

    <!-- Yandex.Metrika counter -->
    {% yandex_metrica %}
    <!-- /Yandex.Metrika counter -->

</head>

<body>
<div class="wrapper">

    <!-- Navigation -->
    <nav>
        <ul id="myMenu" class="myMenu">
            <a href="#" class="logo"><img src={% static "base/img/logo.png" %} alt="logo"></a>
            <li><a href="/">Главная</a></li>
            <li><a href="{% url 'blog:blog_posts_list_url' %}">Статьи</a></li>
            <li><a href="/store">Программы и сервисы</a></li>
            <li><a href="/#contacts">Контакты</a></li>
            <li><a href="/#about">Обо мне</a></li>
            {% if not request.user.is_authenticated %}
                <li><a href="{% url 'account_login' %}"><i class="fa fa-mail-forward"> Вход</i></a></li>
            {% endif %}
            {% if request.user.is_authenticated %}
                <li><a href="{% url 'profile' %}">Личный кабинет</a></li>
                <li><a href="{% url 'account_logout' %}">Выход</a></li>
            {% endif %}
            <li id="btnMenu" class="btnMenu"><a href="#"><i id="btnMenuImg" class="fa fa-angle-double-down"></i></a></li>

        </ul>
    </nav>

    <!-- Main Content -->
    <main>
        {% block content %}{% endblock content %}
        <button onclick="topFunction()" id="myBtn" title="Home"><i class="fa  fa-angle-double-up"></i></button>
    </main>

    <!-- Footer -->
    <footer>
        <p>Copyright &copy; MaxCoder 2019г</p>
    </footer>

</div>

<!-- JavaScript -->
<script src={% static "base/js/base.js" %}></script>
{% block render_js %}{% endblock render_js %}

</body>

</html>