backend/profile/urls.py
from django.urls import path, include
from .views import ProfilePage, LicensePage



urlpatterns = [
    path('profile/', ProfilePage.as_view(), name="profile"),
    path('license/', LicensePage.as_view(), name="license"),
]

maxcoder_config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, ),
    path('', include('backend.pages.urls')),
    path('', include('allauth.urls')),
    path('blog/', include('backend.blog.urls', namespace='blog')),
    path('store/', include('backend.store.urls', namespace='store')),
    path('accounts/', include('backend.profile.urls')),

]

if settings.DEBUG:
    from django.views.static import serve
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

backend/profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
import random
from django.db.models.signals import pre_save


def pre_save_key_email(sender, instance, *args, **kwargs):
    chars = 'abcdefghijklnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890'
    password = ''
    for n in range(4):
        for i in range(4):
            password += random.choice(chars)
        password += '-'
    print(password)
    instance.key = password[:-1]
    if instance.user.email:
        instance.email = instance.user.email


class LicenseBrickDesign(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name=_('User'))
    key = models.SlugField(max_length=19, blank=True, verbose_name=_('Key'))
    computer_name = models.CharField(max_length=250, blank=True, verbose_name=_('Computer name'))
    id_program = models.CharField(max_length=8, blank=True, verbose_name=_('ID program'))
    email = models.EmailField(blank=True, default='xxx@xxx.xx', verbose_name=_('E-mail'))

    class Meta:
        verbose_name = _('Licenses BrickDesigner_BD001')
        verbose_name_plural = _('Licenses BrickDesigner_BD001')

    def __str__(self):
        return self.user.email


pre_save.connect(pre_save_key_email, sender=LicenseBrickDesign)

backend/profile/views.py
from django.shortcuts import render
from django.views.generic import View
from .models import LicenseBrickDesign


class ProfilePage(View):

    def get(self, request):
        pagename = 'MaxCoder'
        return render(request, 'profile/profile.html', {'pagename': pagename})

class LicensePage(View):

    def get(self, request):
        pagename = 'MaxCoder'
        user = request.user
        return render(request, 'profile/license.html', {'pagename': pagename, 'user': user})

src/templates/profile/license.html
{% extends 'base/base.html' %}
{% load static %}

{% block render_css %}
    <link rel="stylesheet" href={% static "account/css/program_license.css" %}>
{% endblock render_css %}

{% block content %}
    <div class="container-fluid">
    <div class="row block__common justify-content-center">

        <div class="col-12 block">
            <div class="row justify-content-md-start justify-content-center">
                <div class="col-4 col-sm-3 col-md-2 col-lg-1">
                    <img src="{% static "account/img/brickdesigner_icon_256.png" %}" alt="Картинка">
                </div>
                <div class="col-12 col-sm-9 col-md-10 col-lg-11 align-content-sm-center">
                    <h3> Brick Design BD001 <span>ver. 1.0 </span></h3>
                    <p>Программа для сборки бесшовных текстур кирпичной кладки, из разноцветных кирпичей (13 цветов) 1
                        НФ на
                        сером растворе.</p>
                </div>
            </div>
        </div>

        <hr>

        {% for z in user.licensebrickdesign_set.all %}
            <div class="col-12 block__license">
                <div class="row justify-content-center">
                    <div class="col-12">
                        <div class="row justify-content-start">
                            <div class="col-12 col-md-5 col-lg-6">
                                <p><span>Лицензионный ключ:</span></p>
                            </div>
                            <div class="col-md-2"></div>
                            <div class="col-12 col-md-5 col-lg-4">
                                <p class="border">{{ z.key }}</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="row justify-content-start">
                            <div class="col-12 col-md-5 col-lg-6">
                                <p><span>Активирован на компьютере:</span></p>
                            </div>
                            <div class="col-md-2"></div>
                            <div class="col-12 col-md-5 col-lg-4">
                                {% if z.computer_name %}
                                <p class="border">{{ z.computer_name }}</p>
                                {% else %}
                                <p class="border">Ключ не активирован</p>
                                {% endif %}
                                <a class="remove__active" href='#'><i class="fa fa-times-circle-o"> Сброс активации</i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
        {% endfor %}

         <div class="col-12 block__license">
                    <div class="row justify-content-start">
                        <div class="col-12 col-md-4">
                            <a class="btn" href='#'>Приобрести лицензию</a>
                        </div>
                        <div class="col-12 col-md-4">
                            <a class="btn" href='#'>Подробнее о программе</a>
                        </div>
                        <div class="col-12 col-md-4">
                            <a class="btn" href='#'>Помощь</a>
                        </div>
                    </div>
         </div>


    </div>
    </div>
{% endblock content %}

src/templates/profile/profile.html
{% extends 'base/base.html' %}
{% load static %}

{% block render_css %}
    <link rel="stylesheet" href={% static "account/css/profile.css" %}>
{% endblock render_css %}

{% block content %}
    <div class="container-fluid">
    <div class="row block__common justify-content-center ">

        <div class="col-12 col-sm-8 col-md-4 col-lg-3 block">
            <a href="{% url 'license' %}">
                <h3>Лицензии</h3>
                <img src="{% static "account/img/license.png" %}" alt="">
            </a>
            <p>Управление вашими лицензиями</p>
        </div>

        <div class="col-12 col-sm-8 col-md-4 col-lg-3 block">
            <a href="#">
                <h3>Профиль</h3>
                <img src="{% static "account/img/profile.png" %}" alt="">
            </a>
            <p>Настройки вашего аккаунта</p>
        </div>

        <div class="col-12 col-sm-8 col-md-4 col-lg-3 block">
            <a href="#">
                <h3>Тех.поддержка</h3>
                <img src="{% static "account/img/teh.png" %}" alt="">
            </a>
            <p>Возникли вопросы? Пишите.</p>
        </div>

    </div>
    </div>


{% endblock content %}